# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '돌고래' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 돌고래
  pod 'SQLite.swift', '~> 0.11.5'
end
